name: flow-deco

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update apt and show users
        run: |
          sudo apt update -y
          sudo cat /etc/passwd

      - name: Create user franck
        run: sudo useradd franck || true

      - name: Create file
        run: touch file1

      - name: Create folder
        run: mkdir -p devops

      - name: Print working directory
        run: pwd
          
          
            
      
